# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1230, 730)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(1230, 730))
        mainWindow.setMaximumSize(QtCore.QSize(1230, 733))
        mainWindow.setAutoFillBackground(False)
        mainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setStyleSheet("background-color : rgb(22, 25, 39)\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Sidebar = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sidebar.sizePolicy().hasHeightForWidth())
        self.Sidebar.setSizePolicy(sizePolicy)
        self.Sidebar.setMaximumSize(QtCore.QSize(298, 16777215))
        self.Sidebar.setStyleSheet("background-color : rgba(101, 108, 131, 30)\n"
"")
        self.Sidebar.setFrameShape(QtWidgets.QFrame.Box)
        self.Sidebar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Sidebar.setLineWidth(-13)
        self.Sidebar.setMidLineWidth(30)
        self.Sidebar.setObjectName("Sidebar")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.Sidebar)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-30, 100, 331, 561))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.SidebarButtons = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.SidebarButtons.setContentsMargins(0, 0, 0, 0)
        self.SidebarButtons.setSpacing(0)
        self.SidebarButtons.setObjectName("SidebarButtons")
        self.HomeButton_35 = QtWidgets.QHBoxLayout()
        self.HomeButton_35.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.HomeButton_35.setContentsMargins(0, 0, -1, -1)
        self.HomeButton_35.setSpacing(6)
        self.HomeButton_35.setObjectName("HomeButton_35")
        self.HomeButton_36 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.HomeButton_36.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.HomeButton_36.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.HomeButton_36.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.HomeButton_36.setIcon(icon)
        self.HomeButton_36.setIconSize(QtCore.QSize(42, 42))
        self.HomeButton_36.setObjectName("HomeButton_36")
        self.HomeButton_35.addWidget(self.HomeButton_36, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.HomeLabel_18 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Futurist Fixed-width")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.HomeLabel_18.setFont(font)
        self.HomeLabel_18.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.HomeLabel_18.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"color: white;\n"
"")
        self.HomeLabel_18.setScaledContents(False)
        self.HomeLabel_18.setAlignment(QtCore.Qt.AlignCenter)
        self.HomeLabel_18.setWordWrap(False)
        self.HomeLabel_18.setIndent(0)
        self.HomeLabel_18.setObjectName("HomeLabel_18")
        self.HomeButton_35.addWidget(self.HomeLabel_18, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.SidebarButtons.addLayout(self.HomeButton_35)
        self.FaceAIButton = QtWidgets.QHBoxLayout()
        self.FaceAIButton.setObjectName("FaceAIButton")
        self.FaceAIButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.FaceAIButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FaceAIButton_2.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.FaceAIButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/face.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FaceAIButton_2.setIcon(icon1)
        self.FaceAIButton_2.setIconSize(QtCore.QSize(42, 42))
        self.FaceAIButton_2.setObjectName("FaceAIButton_2")
        self.FaceAIButton.addWidget(self.FaceAIButton_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.FaceAILabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Futurist Fixed-width")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.FaceAILabel.setFont(font)
        self.FaceAILabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.FaceAILabel.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"color: white;\n"
"")
        self.FaceAILabel.setScaledContents(False)
        self.FaceAILabel.setAlignment(QtCore.Qt.AlignCenter)
        self.FaceAILabel.setWordWrap(False)
        self.FaceAILabel.setIndent(0)
        self.FaceAILabel.setObjectName("FaceAILabel")
        self.FaceAIButton.addWidget(self.FaceAILabel, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.SidebarButtons.addLayout(self.FaceAIButton)
        self.ProductsButton = QtWidgets.QHBoxLayout()
        self.ProductsButton.setObjectName("ProductsButton")
        self.ProductButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.ProductButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ProductButton.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.ProductButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/spa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ProductButton.setIcon(icon2)
        self.ProductButton.setIconSize(QtCore.QSize(42, 42))
        self.ProductButton.setObjectName("ProductButton")
        self.ProductsButton.addWidget(self.ProductButton, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.ProductLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Futurist Fixed-width")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.ProductLabel.setFont(font)
        self.ProductLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ProductLabel.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"color: white;\n"
"")
        self.ProductLabel.setScaledContents(False)
        self.ProductLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ProductLabel.setWordWrap(False)
        self.ProductLabel.setIndent(0)
        self.ProductLabel.setObjectName("ProductLabel")
        self.ProductsButton.addWidget(self.ProductLabel, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.SidebarButtons.addLayout(self.ProductsButton)
        self.TutorialsButton = QtWidgets.QHBoxLayout()
        self.TutorialsButton.setObjectName("TutorialsButton")
        self.TutorialsButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.TutorialsButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.TutorialsButton_2.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.TutorialsButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TutorialsButton_2.setIcon(icon3)
        self.TutorialsButton_2.setIconSize(QtCore.QSize(42, 42))
        self.TutorialsButton_2.setObjectName("TutorialsButton_2")
        self.TutorialsButton.addWidget(self.TutorialsButton_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.TutorialsLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Futurist Fixed-width")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.TutorialsLabel.setFont(font)
        self.TutorialsLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.TutorialsLabel.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"color: white;\n"
"")
        self.TutorialsLabel.setScaledContents(False)
        self.TutorialsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TutorialsLabel.setWordWrap(False)
        self.TutorialsLabel.setIndent(0)
        self.TutorialsLabel.setObjectName("TutorialsLabel")
        self.TutorialsButton.addWidget(self.TutorialsLabel, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.SidebarButtons.addLayout(self.TutorialsButton)
        self.ArticlesButton = QtWidgets.QHBoxLayout()
        self.ArticlesButton.setObjectName("ArticlesButton")
        self.ArticlesButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.ArticlesButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ArticlesButton_2.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.ArticlesButton_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/web.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ArticlesButton_2.setIcon(icon4)
        self.ArticlesButton_2.setIconSize(QtCore.QSize(42, 42))
        self.ArticlesButton_2.setObjectName("ArticlesButton_2")
        self.ArticlesButton.addWidget(self.ArticlesButton_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.ArticlesLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Futurist Fixed-width")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.ArticlesLabel.setFont(font)
        self.ArticlesLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ArticlesLabel.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"color: white;\n"
"")
        self.ArticlesLabel.setScaledContents(False)
        self.ArticlesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ArticlesLabel.setWordWrap(False)
        self.ArticlesLabel.setIndent(0)
        self.ArticlesLabel.setObjectName("ArticlesLabel")
        self.ArticlesButton.addWidget(self.ArticlesLabel, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.SidebarButtons.addLayout(self.ArticlesButton)
        self.QuizButton = QtWidgets.QHBoxLayout()
        self.QuizButton.setObjectName("QuizButton")
        self.QuizButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.QuizButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.QuizButton_2.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.QuizButton_2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QuizButton_2.setIcon(icon5)
        self.QuizButton_2.setIconSize(QtCore.QSize(42, 42))
        self.QuizButton_2.setObjectName("QuizButton_2")
        self.QuizButton.addWidget(self.QuizButton_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.QuizLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Futurist Fixed-width")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.QuizLabel.setFont(font)
        self.QuizLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.QuizLabel.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"color: white;\n"
"")
        self.QuizLabel.setScaledContents(False)
        self.QuizLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.QuizLabel.setWordWrap(False)
        self.QuizLabel.setIndent(0)
        self.QuizLabel.setObjectName("QuizLabel")
        self.QuizButton.addWidget(self.QuizLabel, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.SidebarButtons.addLayout(self.QuizButton)
        self.MapButton = QtWidgets.QHBoxLayout()
        self.MapButton.setObjectName("MapButton")
        self.MapButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.MapButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MapButton_2.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.MapButton_2.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/map.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MapButton_2.setIcon(icon6)
        self.MapButton_2.setIconSize(QtCore.QSize(42, 42))
        self.MapButton_2.setObjectName("MapButton_2")
        self.MapButton.addWidget(self.MapButton_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.MapLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Futurist Fixed-width")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.MapLabel.setFont(font)
        self.MapLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.MapLabel.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"color: white;\n"
"")
        self.MapLabel.setScaledContents(False)
        self.MapLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MapLabel.setWordWrap(False)
        self.MapLabel.setIndent(0)
        self.MapLabel.setObjectName("MapLabel")
        self.MapButton.addWidget(self.MapLabel, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.SidebarButtons.addLayout(self.MapButton)
        self.StatsButton = QtWidgets.QHBoxLayout()
        self.StatsButton.setObjectName("StatsButton")
        self.StatsButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.StatsButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.StatsButton_2.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.StatsButton_2.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/stats.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.StatsButton_2.setIcon(icon7)
        self.StatsButton_2.setIconSize(QtCore.QSize(42, 42))
        self.StatsButton_2.setObjectName("StatsButton_2")
        self.StatsButton.addWidget(self.StatsButton_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.StatsLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Futurist Fixed-width")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.StatsLabel.setFont(font)
        self.StatsLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.StatsLabel.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"color: white;\n"
"")
        self.StatsLabel.setScaledContents(False)
        self.StatsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.StatsLabel.setWordWrap(False)
        self.StatsLabel.setIndent(0)
        self.StatsLabel.setObjectName("StatsLabel")
        self.StatsButton.addWidget(self.StatsLabel, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.SidebarButtons.addLayout(self.StatsButton)
        self.SidebarIcon = QtWidgets.QLabel(self.Sidebar)
        self.SidebarIcon.setGeometry(QtCore.QRect(37, 24, 221, 48))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SidebarIcon.sizePolicy().hasHeightForWidth())
        self.SidebarIcon.setSizePolicy(sizePolicy)
        self.SidebarIcon.setMaximumSize(QtCore.QSize(400, 88))
        self.SidebarIcon.setAutoFillBackground(False)
        self.SidebarIcon.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.SidebarIcon.setFrameShadow(QtWidgets.QFrame.Plain)
        self.SidebarIcon.setLineWidth(0)
        self.SidebarIcon.setText("")
        self.SidebarIcon.setPixmap(QtGui.QPixmap(":/images/logo.png"))
        self.SidebarIcon.setScaledContents(True)
        self.SidebarIcon.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.SidebarIcon.setWordWrap(False)
        self.SidebarIcon.setIndent(0)
        self.SidebarIcon.setObjectName("SidebarIcon")
        self.BackButton = QtWidgets.QPushButton(self.Sidebar)
        self.BackButton.setGeometry(QtCore.QRect(120, 670, 54, 50))
        self.BackButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BackButton.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.BackButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BackButton.setIcon(icon8)
        self.BackButton.setIconSize(QtCore.QSize(42, 42))
        self.BackButton.setObjectName("BackButton")
        self.horizontalLayout.addWidget(self.Sidebar)
        self.UserPage = QtWidgets.QFrame(self.centralwidget)
        self.UserPage.setEnabled(True)
        self.UserPage.setStyleSheet("")
        self.UserPage.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.UserPage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.UserPage.setLineWidth(0)
        self.UserPage.setObjectName("UserPage")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.UserPage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 901, 711))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.UserLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.UserLayout.setContentsMargins(0, 0, 0, 0)
        self.UserLayout.setSpacing(0)
        self.UserLayout.setObjectName("UserLayout")
        self.UserPageIcon = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.UserPageIcon.setMinimumSize(QtCore.QSize(80, 80))
        self.UserPageIcon.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.UserPageIcon.setFont(font)
        self.UserPageIcon.setText("")
        self.UserPageIcon.setPixmap(QtGui.QPixmap(":/icons/C:/Users/Sebastian/PycharmProjects/FaceAI/Assets/Icons/userIcon.png"))
        self.UserPageIcon.setScaledContents(True)
        self.UserPageIcon.setObjectName("UserPageIcon")
        self.UserLayout.addWidget(self.UserPageIcon, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.UserPageName = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Futurist Fixed-width")
        font.setPointSize(24)
        self.UserPageName.setFont(font)
        self.UserPageName.setStyleSheet("color: white")
        self.UserPageName.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.UserPageName.setWordWrap(True)
        self.UserPageName.setObjectName("UserPageName")
        self.UserLayout.addWidget(self.UserPageName)
        self.UserInfoFrame = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.UserInfoFrame.setMinimumSize(QtCore.QSize(900, 500))
        self.UserInfoFrame.setMaximumSize(QtCore.QSize(900, 500))
        self.UserInfoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.UserInfoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.UserInfoFrame.setObjectName("UserInfoFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.UserInfoFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.UserInfoLayout = QtWidgets.QGridLayout()
        self.UserInfoLayout.setSpacing(10)
        self.UserInfoLayout.setObjectName("UserInfoLayout")
        self.FavTutorialsSide = QtWidgets.QFrame(self.UserInfoFrame)
        self.FavTutorialsSide.setStyleSheet("border: 1px solid white;\n"
"border-radius: 15px;")
        self.FavTutorialsSide.setObjectName("FavTutorialsSide")
        self.FavTutorialsPage = QtWidgets.QVBoxLayout(self.FavTutorialsSide)
        self.FavTutorialsPage.setObjectName("FavTutorialsPage")
        self.FavTutorialsButton = QtWidgets.QPushButton(self.FavTutorialsSide)
        self.FavTutorialsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FavTutorialsButton.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;")
        self.FavTutorialsButton.setText("")
        self.FavTutorialsButton.setIcon(icon3)
        self.FavTutorialsButton.setIconSize(QtCore.QSize(42, 42))
        self.FavTutorialsButton.setObjectName("FavTutorialsButton")
        self.FavTutorialsPage.addWidget(self.FavTutorialsButton)
        self.FavTutorialsScrollArea = QtWidgets.QScrollArea(self.FavTutorialsSide)
        self.FavTutorialsScrollArea.setMinimumSize(QtCore.QSize(400, 176))
        self.FavTutorialsScrollArea.setMaximumSize(QtCore.QSize(400, 176))
        self.FavTutorialsScrollArea.setStyleSheet("border: none")
        self.FavTutorialsScrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.FavTutorialsScrollArea.setWidgetResizable(True)
        self.FavTutorialsScrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.FavTutorialsScrollArea.setObjectName("FavTutorialsScrollArea")
        self.FavTutorialsScrollContents = QtWidgets.QWidget()
        self.FavTutorialsScrollContents.setGeometry(QtCore.QRect(0, 0, 400, 176))
        self.FavTutorialsScrollContents.setObjectName("FavTutorialsScrollContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.FavTutorialsScrollContents)
        self.verticalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_4.setSpacing(34)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.FavTutorialItem = QtWidgets.QFrame(self.FavTutorialsScrollContents)
        self.FavTutorialItem.setMinimumSize(QtCore.QSize(372, 80))
        self.FavTutorialItem.setMaximumSize(QtCore.QSize(372, 80))
        self.FavTutorialItem.setStyleSheet("border: 1px solid white;\n"
"border-top-right-radius: 0;\n"
"border-bottom-right-radius: 0;")
        self.FavTutorialItem.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FavTutorialItem.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FavTutorialItem.setObjectName("FavTutorialItem")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.FavTutorialItem)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.FavTutorialItemTitle = QtWidgets.QLabel(self.FavTutorialItem)
        self.FavTutorialItemTitle.setMinimumSize(QtCore.QSize(270, 78))
        self.FavTutorialItemTitle.setMaximumSize(QtCore.QSize(270, 78))
        font = QtGui.QFont()
        font.setFamily("Futurist Fixed-width")
        self.FavTutorialItemTitle.setFont(font)
        self.FavTutorialItemTitle.setStyleSheet("border: none;\n"
"color: white;")
        self.FavTutorialItemTitle.setScaledContents(False)
        self.FavTutorialItemTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.FavTutorialItemTitle.setWordWrap(True)
        self.FavTutorialItemTitle.setIndent(0)
        self.FavTutorialItemTitle.setObjectName("FavTutorialItemTitle")
        self.horizontalLayout_3.addWidget(self.FavTutorialItemTitle)
        self.FavTutorialItemImage = QtWidgets.QLabel(self.FavTutorialItem)
        self.FavTutorialItemImage.setMinimumSize(QtCore.QSize(100, 0))
        self.FavTutorialItemImage.setMaximumSize(QtCore.QSize(100, 80))
        self.FavTutorialItemImage.setStyleSheet("border: none;")
        self.FavTutorialItemImage.setText("")
        self.FavTutorialItemImage.setPixmap(QtGui.QPixmap(":/images/faceOil.png"))
        self.FavTutorialItemImage.setScaledContents(True)
        self.FavTutorialItemImage.setAlignment(QtCore.Qt.AlignCenter)
        self.FavTutorialItemImage.setObjectName("FavTutorialItemImage")
        self.horizontalLayout_3.addWidget(self.FavTutorialItemImage)
        self.verticalLayout_4.addWidget(self.FavTutorialItem)
        self.FavTutorialsScrollArea.setWidget(self.FavTutorialsScrollContents)
        self.FavTutorialsPage.addWidget(self.FavTutorialsScrollArea, 0, QtCore.Qt.AlignHCenter)
        self.UserInfoLayout.addWidget(self.FavTutorialsSide, 1, 1, 1, 1)
        self.QuizResultSide = QtWidgets.QFrame(self.UserInfoFrame)
        self.QuizResultSide.setStyleSheet("border: 1px solid white;\n"
"border-radius: 15px;")
        self.QuizResultSide.setObjectName("QuizResultSide")
        self.QuizResultPage = QtWidgets.QVBoxLayout(self.QuizResultSide)
        self.QuizResultPage.setObjectName("QuizResultPage")
        self.QuizResultButton = QtWidgets.QPushButton(self.QuizResultSide)
        self.QuizResultButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.QuizResultButton.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;")
        self.QuizResultButton.setText("")
        self.QuizResultButton.setIcon(icon5)
        self.QuizResultButton.setIconSize(QtCore.QSize(42, 42))
        self.QuizResultButton.setObjectName("QuizResultButton")
        self.QuizResultPage.addWidget(self.QuizResultButton)
        self.QuizResultTitle = QtWidgets.QLabel(self.QuizResultSide)
        font = QtGui.QFont()
        font.setFamily("Futurist Fixed-width")
        font.setPointSize(13)
        self.QuizResultTitle.setFont(font)
        self.QuizResultTitle.setStyleSheet("border: none;\n"
"color: white;")
        self.QuizResultTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.QuizResultTitle.setWordWrap(True)
        self.QuizResultTitle.setObjectName("QuizResultTitle")
        self.QuizResultPage.addWidget(self.QuizResultTitle)
        self.QuizResultText = QtWidgets.QLabel(self.QuizResultSide)
        font = QtGui.QFont()
        font.setFamily("Futurist Fixed-width")
        font.setPointSize(12)
        self.QuizResultText.setFont(font)
        self.QuizResultText.setStyleSheet("border: none;\n"
"color: white;")
        self.QuizResultText.setAlignment(QtCore.Qt.AlignCenter)
        self.QuizResultText.setWordWrap(True)
        self.QuizResultText.setObjectName("QuizResultText")
        self.QuizResultPage.addWidget(self.QuizResultText)
        self.UserInfoLayout.addWidget(self.QuizResultSide, 2, 1, 1, 1)
        self.FavProductsSide = QtWidgets.QFrame(self.UserInfoFrame)
        self.FavProductsSide.setStyleSheet("border: 1px solid white;\n"
"border-radius: 15px;")
        self.FavProductsSide.setObjectName("FavProductsSide")
        self.FavProductsPage = QtWidgets.QVBoxLayout(self.FavProductsSide)
        self.FavProductsPage.setObjectName("FavProductsPage")
        self.FavProductsButton = QtWidgets.QPushButton(self.FavProductsSide)
        self.FavProductsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FavProductsButton.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;")
        self.FavProductsButton.setText("")
        self.FavProductsButton.setIcon(icon2)
        self.FavProductsButton.setIconSize(QtCore.QSize(42, 42))
        self.FavProductsButton.setObjectName("FavProductsButton")
        self.FavProductsPage.addWidget(self.FavProductsButton)
        self.FavProductsScrollArea = QtWidgets.QScrollArea(self.FavProductsSide)
        self.FavProductsScrollArea.setMinimumSize(QtCore.QSize(400, 176))
        self.FavProductsScrollArea.setMaximumSize(QtCore.QSize(400, 176))
        self.FavProductsScrollArea.setStyleSheet("border: none")
        self.FavProductsScrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.FavProductsScrollArea.setWidgetResizable(True)
        self.FavProductsScrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.FavProductsScrollArea.setObjectName("FavProductsScrollArea")
        self.FavProductsScrollContents = QtWidgets.QWidget()
        self.FavProductsScrollContents.setGeometry(QtCore.QRect(0, 0, 400, 176))
        self.FavProductsScrollContents.setObjectName("FavProductsScrollContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.FavProductsScrollContents)
        self.verticalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_3.setSpacing(34)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.FavProductItem = QtWidgets.QFrame(self.FavProductsScrollContents)
        self.FavProductItem.setMinimumSize(QtCore.QSize(372, 80))
        self.FavProductItem.setMaximumSize(QtCore.QSize(372, 80))
        self.FavProductItem.setStyleSheet("border: 1px solid white;\n"
"border-top-right-radius: 0;\n"
"border-bottom-right-radius: 0;")
        self.FavProductItem.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FavProductItem.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FavProductItem.setObjectName("FavProductItem")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.FavProductItem)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.FavProdItemTitle = QtWidgets.QLabel(self.FavProductItem)
        self.FavProdItemTitle.setMinimumSize(QtCore.QSize(270, 78))
        self.FavProdItemTitle.setMaximumSize(QtCore.QSize(270, 78))
        font = QtGui.QFont()
        font.setFamily("Futurist Fixed-width")
        self.FavProdItemTitle.setFont(font)
        self.FavProdItemTitle.setStyleSheet("border: none;\n"
"color: white;")
        self.FavProdItemTitle.setScaledContents(False)
        self.FavProdItemTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.FavProdItemTitle.setWordWrap(True)
        self.FavProdItemTitle.setIndent(0)
        self.FavProdItemTitle.setObjectName("FavProdItemTitle")
        self.horizontalLayout_2.addWidget(self.FavProdItemTitle)
        self.FavProdItemImage = QtWidgets.QLabel(self.FavProductItem)
        self.FavProdItemImage.setMinimumSize(QtCore.QSize(100, 0))
        self.FavProdItemImage.setMaximumSize(QtCore.QSize(100, 80))
        self.FavProdItemImage.setStyleSheet("border: none;")
        self.FavProdItemImage.setText("")
        self.FavProdItemImage.setPixmap(QtGui.QPixmap(":/images/faceOil.png"))
        self.FavProdItemImage.setScaledContents(True)
        self.FavProdItemImage.setAlignment(QtCore.Qt.AlignCenter)
        self.FavProdItemImage.setObjectName("FavProdItemImage")
        self.horizontalLayout_2.addWidget(self.FavProdItemImage)
        self.verticalLayout_3.addWidget(self.FavProductItem)
        self.FavProductsScrollArea.setWidget(self.FavProductsScrollContents)
        self.FavProductsPage.addWidget(self.FavProductsScrollArea, 0, QtCore.Qt.AlignHCenter)
        self.UserInfoLayout.addWidget(self.FavProductsSide, 1, 0, 1, 1)
        self.FavArticlesSide = QtWidgets.QFrame(self.UserInfoFrame)
        self.FavArticlesSide.setStyleSheet("border: 1px solid white;\n"
"border-radius: 15px;")
        self.FavArticlesSide.setObjectName("FavArticlesSide")
        self.FavArticlesPage = QtWidgets.QVBoxLayout(self.FavArticlesSide)
        self.FavArticlesPage.setObjectName("FavArticlesPage")
        self.FavArticlesButton = QtWidgets.QPushButton(self.FavArticlesSide)
        self.FavArticlesButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FavArticlesButton.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;")
        self.FavArticlesButton.setText("")
        self.FavArticlesButton.setIcon(icon4)
        self.FavArticlesButton.setIconSize(QtCore.QSize(42, 42))
        self.FavArticlesButton.setObjectName("FavArticlesButton")
        self.FavArticlesPage.addWidget(self.FavArticlesButton)
        self.FavArticlesScrollArea = QtWidgets.QScrollArea(self.FavArticlesSide)
        self.FavArticlesScrollArea.setMinimumSize(QtCore.QSize(400, 176))
        self.FavArticlesScrollArea.setMaximumSize(QtCore.QSize(400, 176))
        self.FavArticlesScrollArea.setStyleSheet("border: none")
        self.FavArticlesScrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.FavArticlesScrollArea.setWidgetResizable(True)
        self.FavArticlesScrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.FavArticlesScrollArea.setObjectName("FavArticlesScrollArea")
        self.FavArticlesScrollContents = QtWidgets.QWidget()
        self.FavArticlesScrollContents.setGeometry(QtCore.QRect(0, 0, 400, 176))
        self.FavArticlesScrollContents.setObjectName("FavArticlesScrollContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.FavArticlesScrollContents)
        self.verticalLayout_5.setContentsMargins(0, -1, 9, -1)
        self.verticalLayout_5.setSpacing(34)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.FavProductItem_3 = QtWidgets.QFrame(self.FavArticlesScrollContents)
        self.FavProductItem_3.setMinimumSize(QtCore.QSize(372, 80))
        self.FavProductItem_3.setMaximumSize(QtCore.QSize(372, 80))
        self.FavProductItem_3.setStyleSheet("border: 1px solid white;\n"
"border-top-right-radius: 0;\n"
"border-bottom-right-radius: 0;")
        self.FavProductItem_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FavProductItem_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FavProductItem_3.setObjectName("FavProductItem_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.FavProductItem_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.FavProdItemTitle_3 = QtWidgets.QLabel(self.FavProductItem_3)
        self.FavProdItemTitle_3.setMinimumSize(QtCore.QSize(270, 78))
        self.FavProdItemTitle_3.setMaximumSize(QtCore.QSize(270, 78))
        font = QtGui.QFont()
        font.setFamily("Futurist Fixed-width")
        font.setPointSize(7)
        self.FavProdItemTitle_3.setFont(font)
        self.FavProdItemTitle_3.setStyleSheet("border: none;\n"
"color: white;")
        self.FavProdItemTitle_3.setScaledContents(False)
        self.FavProdItemTitle_3.setAlignment(QtCore.Qt.AlignCenter)
        self.FavProdItemTitle_3.setWordWrap(True)
        self.FavProdItemTitle_3.setIndent(0)
        self.FavProdItemTitle_3.setObjectName("FavProdItemTitle_3")
        self.horizontalLayout_4.addWidget(self.FavProdItemTitle_3)
        self.FavProdItemImage_3 = QtWidgets.QLabel(self.FavProductItem_3)
        self.FavProdItemImage_3.setMinimumSize(QtCore.QSize(100, 0))
        self.FavProdItemImage_3.setMaximumSize(QtCore.QSize(100, 80))
        self.FavProdItemImage_3.setStyleSheet("border: none;")
        self.FavProdItemImage_3.setText("")
        self.FavProdItemImage_3.setPixmap(QtGui.QPixmap(":/images/faceOil.png"))
        self.FavProdItemImage_3.setScaledContents(True)
        self.FavProdItemImage_3.setAlignment(QtCore.Qt.AlignCenter)
        self.FavProdItemImage_3.setObjectName("FavProdItemImage_3")
        self.horizontalLayout_4.addWidget(self.FavProdItemImage_3)
        self.verticalLayout_5.addWidget(self.FavProductItem_3)
        self.FavArticlesScrollArea.setWidget(self.FavArticlesScrollContents)
        self.FavArticlesPage.addWidget(self.FavArticlesScrollArea, 0, QtCore.Qt.AlignHCenter)
        self.UserInfoLayout.addWidget(self.FavArticlesSide, 2, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.UserInfoLayout)
        self.UserLayout.addWidget(self.UserInfoFrame)
        self.horizontalLayout.addWidget(self.UserPage)
        self.verticalLayout.addLayout(self.horizontalLayout)
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Face AI"))
        self.HomeLabel_18.setText(_translate("mainWindow", "HOME"))
        self.FaceAILabel.setText(_translate("mainWindow", "FACE SCAN"))
        self.ProductLabel.setText(_translate("mainWindow", "PRODUCTS"))
        self.TutorialsLabel.setText(_translate("mainWindow", "TUTORIALS"))
        self.ArticlesLabel.setText(_translate("mainWindow", "ARTICLES"))
        self.QuizLabel.setText(_translate("mainWindow", "QUIZ"))
        self.MapLabel.setText(_translate("mainWindow", "HELP MAP"))
        self.StatsLabel.setText(_translate("mainWindow", "STATS"))
        self.UserPageName.setText(_translate("mainWindow", "Sebastian"))
        self.FavTutorialItemTitle.setText(_translate("mainWindow", "How To Remove Whiteheads"))
        self.QuizResultTitle.setText(_translate("mainWindow", "Your type of skin is:"))
        self.QuizResultText.setText(_translate("mainWindow", "Oily Skin"))
        self.FavProdItemTitle.setText(_translate("mainWindow", "Gentle Black Deep Cleansing Oil"))
        self.FavProdItemTitle_3.setText(_translate("mainWindow", "Pimple Patch, How Does It Work and Why You Need One at All Times"))
import Assets_rc
